```{r}
library(here)
library(sp)
library(rgeos)
library(maptools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(janitor)
library(stringr)
library(tidyverse)
library(readr)
library(dplyr)
library(rgdal)
library(sp)
library(ggplot2)
library(janitor)
```

```{r}
Ohio_Shape <- st_read(here::here("Police_Precincts/Police_Precincts.shp"))
Ohio_Shape <- st_transform(Ohio_Shape, 4326)
Police_Data <- read.csv(here::here("oh_columbus_2020_04_01.csv")) %>%
  replace(., . == "", NA) %>%
  clean_names() %>%
  filter(!is.na(lat), !is.na(lng), !is.na(zone))
Police_Data <- st_as_sf(Police_Data, coords = c("lng", "lat"), crs = 4326)

Police_Data_2012 <- Police_Data %>%
  filter(grepl("^2012-", date))  # 筛选2012年的数据


sf_use_s2(FALSE)
tmap_mode("plot")
tm_shape(Ohio_Shape) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(Police_Data_2012) +
  tm_dots(col = "blue", size = 0.003)
```

```{r}
Police_Data_2016 <- Police_Data %>%
  filter(grepl("^2016-", date))  # 筛选2012年的数据


sf_use_s2(FALSE)
tmap_mode("plot")
tm_shape(Ohio_Shape) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(Police_Data_2016) +
  tm_dots(col = "red", size = 0.003)
```
K密度
```{r}
# 2012
library(spatstat)
Police_Data_2012 <- st_transform(Police_Data_2012, crs = 2823)
Ohio_Shape <- st_transform(Ohio_Shape, crs = 2823)
window <- as.owin(Ohio_Shape)

Police_Data_2012_Spatial <- as(Police_Data_2012, "Spatial")

coords <- coordinates(Police_Data_2012_Spatial)

Police_Data_2012_Spatial.ppp <- ppp(x = coords[,1], y = coords[,2], window = window)

Police_Data_2012_Density <- density(Police_Data_2012_Spatial.ppp, sigma = 1500)
plot(Police_Data_2012_Density)
```


```{r}
# 2016
library(spatstat)
Police_Data_2016 <- st_transform(Police_Data_2016, crs = 2823)
Ohio_Shape <- st_transform(Ohio_Shape, crs = 2823)
window <- as.owin(Ohio_Shape)

Police_Data_2016_Spatial <- as(Police_Data_2016, "Spatial")

coords <- coordinates(Police_Data_2016_Spatial)

Police_Data_2016_Spatial.ppp <- ppp(x = coords[,1], y = coords[,2], window = window)

Police_Data_2016_Density <- density(Police_Data_2016_Spatial.ppp, sigma = 1500)
plot(Police_Data_2016_Density)
```


```{r}
K <- Police_Data_2016_Spatial.ppp %>%
  Kest(.,correction = "border") %>%
  plot()
```

```{r}
K <- Police_Data_2012_Spatial.ppp %>%
  Kest(.,correction = "border") %>%
  plot()
```

```{r}
Police_Data_2012_SpatialSubPoints <- Police_Data_2012_Spatial%>%
  coordinates(.)%>%
  as.data.frame()
db <- Police_Data_2012_SpatialSubPoints%>%
  fpc::dbscan(.,eps = 900, MinPts = 5)
plot(db, Police_Data_2012_SpatialSubPoints, main = "DBSCAN Output", frame = F)
plot(Ohio_Shape$geometry, add=T)
```

